version: "3.7"

# This is an example compose file, statically defined just for tests with a USB camera
services:
  data-source-mjpg:
    build: .
    command: --device-path /dev/video0 --input-type input_uvc.so --resolution 1280x720 --fps 15
    networks:
      - nuvlabox-shared-network
    devices:
      - /dev/video0
    labels:
      - nuvlabox.component=False
      - "traefik.enable=true"
      - "traefik.http.routers.mjpg-streamer-video0-router.rule=Host(`data-gateway`) && PathPrefix(`/video/video0`)"
      - "traefik.http.routers.mjpg-streamer-video0-router.entrypoints=web"
      - "traefik.http.routers.mjpg-streamer-video0-router.middlewares=video0-mid"
      - "traefik.http.services.mjpg-streamer-video0-service.loadbalancer.server.port=8082"
      - "traefik.http.services.mjpg-streamer-video0-service.loadbalancer.healthcheck.port=8082"
      - "traefik.http.services.mjpg-streamer-video0-service.loadbalancer.healthcheck.path=/"
      - "traefik.http.middlewares.video0-mid.replacepath.path=/"
    restart: on-failure


networks:
  nuvlabox-shared-network:
    external:
      name: nuvlabox-shared-network


